config/routes.rb
Rails.application.routes.draw do

  resources :statuses

  get '/index' => 'user#index'

  get ':username/friends' => 'user#friends'

  get '/add_friend' => 'user#add_friend'

  get '/find_friends' => 'user#find_friends'

  get '/accept_request' => 'user#accept_request'

  get '/deny_request' => 'user#deny_request'

  get '/voting' => 'user#votes'

  get ':username/friend_requests' => 'user#friend_requests'

  get ':username' => 'user#show', as: :user

  get 'welcome/index'

  devise_for :users

  root 'welcome#index'


end

app/models/status.rb
class Status < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  include Amistad::FriendModel
  has_many :statuses

  def add_friend
    binding.pry
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << :username
     devise_parameter_sanitizer.for(:sign_up) << :name
     devise_parameter_sanitizer.for(:sign_up) << :gender
     devise_parameter_sanitizer.for(:sign_up) << :birthday
     devise_parameter_sanitizer.for(:sign_up) << :city
     devise_parameter_sanitizer.for(:sign_up) << :state
     devise_parameter_sanitizer.for(:sign_up) << :country
     devise_parameter_sanitizer.for(:sign_up) << :image_location
   end

   def after_sign_in_path_for(resource)
     index_path #your path
   end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController

  def index
  end

  def new
    @status = Status.new
  end

  def create
    if params[:status][:status_update] == "something"
      params[:status][:status_update] = LiterateRandomizer.sentence
    elsif params[:status][:status_update] == "something-smart"
      params[:status][:status_update] = Faker::Hacker.say_something_smart
    elsif params[:status][:status_update] == "something-short"
      params[:status][:status_update] = Faker::Company.catch_phrase
    elsif params[:status][:status_update] == "something-long"
      params[:status][:status_update] = LiterateRandomizer.paragraph
    elsif params[:status][:status_update] == "something-latin"
      params[:status][:status_update] = Faker::Lorem.sentence
    end
    @status = Status.new(status_params)
      if @status.save
        render(json: {message: 'Status updated', post: params[:status][:status_update]})
      else
        render(json: {message: 'ERROR, NO UPDATE'}, status: 418)
      end
  end

  def destroy
  end

  def update
  end

  def edit
  end

  private
  def status_params
    params.require(:status).permit(:status_update, :user_id)
  end


end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def index
    @users = User.all
    @statuses = Status.all.order(created_at: :desc)
  end

  def show
    @user = User.find_by(username: params[:username])
    @statuses = @user.statuses.order(created_at: :desc)
  end

  def friends
    @user = User.find_by(username: params[:username])
    @user_friends = @user.friends
  end

  def add_friend
    @user = User.find_by(username: params[:format])
    current_user.invite @user
    redirect_to user_path(@user.username)
  end

  def friend_requests
    @user = User.find_by(username: params[:username])
    @requests = @user.pending_invited_by
  end

  def accept_request
    @user = User.find_by(username: params[:username])
    @friend = User.find_by(username: params[:friend_name])
    @user.approve @friend
    redirect_to index_path
  end

  def deny_request
    @user = User.find_by(username: params[:username])
    @friend = User.find_by(username: params[:friend_name])
    @user.block @friend
    redirect_to index_path
  end


  def find_friends
    @users = User.paginate(:page => params[:page], :per_page => 4)
  end

  def votes
    @status = Status.find_by(id: params[:status])
    @voter = User.find_by(username: params[:voter])
    if params[:votes].to_i > 0
      @status.liked_by @voter
      upvotes = @status.get_upvotes.size.to_i
      downvotes = @status.get_downvotes.size.to_i
      total = upvotes - downvotes
      render(json: {total_votes: total}, status: 200)
    else
      @status.downvote_from @voter
      upvotes = @status.get_upvotes.size
      downvotes = @status.get_downvotes.size
      total = upvotes - downvotes
      render(json: {total_votes: total}, status: 200)
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navbar.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <% if current_user %>
        <h1><a href="/index">Fakebook </a></h1>
      <% else %>
        <h1><a href="/">Fakebook </a></h1>
      <% end %>
    </li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Left Nav Section -->
    <ul class="left">
      <li class="divider"></li>
      <% if current_user %>
        <li><%= link_to 'My Profile', user_path(current_user.username) %></li>
        <li class="divider"></li>
        <li>  <%= link_to 'See all friends', '/' + current_user.username + '/friends' %></li>
        <li class="divider"></li>
        <li><%= link_to 'Find Friends', find_friends_path %></a>
      <% end %>

        <ul class="dropdown">
          <li class="has-dropdown"><a href="#">Dropdown Level 1a</a>

            <ul class="dropdown">
              <li><label>Dropdown Level 2 Label</label></li>
              <li><a href="#">Dropdown Level 2a</a></li>
              <li><a href="#">Dropdown Level 2b</a></li>
              <li class="has-dropdown"><a href="#">Dropdown Level 2c</a>

                <ul class="dropdown">
                  <li><label>Dropdown Level 3 Label</label></li>
                  <li><a href="#">Dropdown Level 3a</a></li>
                  <li><a href="#">Dropdown Level 3b</a></li>
                  <li class="divider"></li>
                  <li><a href="#">Dropdown Level 3c</a></li>
                </ul>
              </li>
              <li><a href="#">Dropdown Level 2d</a></li>
              <li><a href="#">Dropdown Level 2e</a></li>
              <li><a href="#">Dropdown Level 2f</a></li>
            </ul>
          </li>
          <li><a href="#">Dropdown Level 1b</a></li>
          <li><a href="#">Dropdown Level 1c</a></li>
          <li class="divider"></li>
          <li><a href="#">Dropdown Level 1d</a></li>
          <li><a href="#">Dropdown Level 1e</a></li>
          <li><a href="#">Dropdown Level 1f</a></li>
          <li class="divider"></li>
          <li><a href="#">See all &rarr;</a></li>
        </ul>
      </li>
      <li class="divider"></li>
    </ul>

    <!-- Right Nav Section -->
    <ul class="right">
      <li class="divider hide-for-small"></li>
      <% if current_user %>
        <li class='friend-requests'><%= link_to current_user.pending_invited_by.count, '/' + current_user.username + '/friend_requests' %></li>
      <% end %>

      <li class="divider"></li>
      <li class="has-form">
        <form>
          <div class="row collapse">
          </div>
        </form>
      </li>
      <li class="divider show-for-small"></li>
      <span class='side-of-nav'>
        <% if current_user %>
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'small button secondary radius' %>
        <% else %>
          <%= link_to 'Sign up', new_user_registration_path, class: 'small button secondary radius' %>
          <%= link_to 'Sign in', new_user_session_path, class: 'small button secondary radius'%>
        <% end %>
      </span>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

    <footer>

    </footer>

  </body>
</html>

app/views/user/find_friends.html.erb
<div class='row'>
  <% @users.each do |user| %>
    <div class="small-3 columns">
      <img src="<%= user.image_location %>" height="100" width="100" ><br><%= link_to user.name, user_path(user.username) %> <br> <i class='text-center'><%= user.username %></i>  <a href="<%= add_friend_path(user.username) %>"><i class="fa fa-plus-circle"></i>Add</a>
    </div>
  <% end %>
</div>

<div class="row text-center">
    <p class='text-center'><%= will_paginate @users %></p>
</div>

app/views/user/friend_requests.html.erb
<table>
<% @requests.each do |request| %>
  <tr><td> <img src="<%= request.image_location %>" height="100" width="100" ><br><%= link_to request.name, user_path(request.username) %> <br> <i class='text-center'><%= request.username %></i>
  <br> <%= link_to 'Accept', accept_request_path({username: current_user.username, friend_name: request.username}), class: 'button tiny success' %> | <%= link_to 'Deny', deny_request_path({username: current_user.username, friend_name: request.username}), class: 'button tiny alert' %>

   </td>
  </tr>
<% end %>
</table>

app/views/user/friends.html.erb
<div class="small-3 columns text-left">
  <table>
    <% @user_friends.each do |friend| %>
      <tr>
        <td> <img src="<%= friend.image_location %>" height="100" width="100" ><br><%= link_to friend.name, user_path(friend.username) %> <br> <i class='text-center'><%= friend.username %></i> </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/user/index.html.erb
<div class="row">
  <div class="small-12 medium-3 large-3 columns text-left">
    <img src="<%= current_user.image_location %>" />
  </div>
  <div class="small-12 medium-3 large-3 columns">
    <%= current_user.name %> ~
    <i>"<%= current_user.username %>"</i><br>
    <%= current_user.city %>, <%= current_user.state %>, <%= current_user.country %><br>
    Born on <%= current_user.birthday.strftime('%b %d, %Y') %><br>
    <%= Time.now.year.to_i - current_user.birthday.strftime('%Y').to_i%> years old<br>
    <%= current_user.gender %><br>
    <%= current_user.friends.count %> total friends <br>
    <%= link_to 'See all friends', '/' + current_user.username + '/friends' %>
  </div>
  <div class="small-12 medium-6 large-6 columns">
    <a class="[tiny small medium large] [secondary alert success] [radius round] button split">Posts <span data-dropdown="drop"></span></a><br>
      <ul id="drop" class="f-dropdown" data-dropdown-content>
        <li><a class='post-something' data-post="something" data-user="<%= current_user.id %>" data-username="<%= current_user.username %>" data-image="<%= current_user.image_location %>">Post Something</a></li>
        <li><a class='post-something-smart' data-post="something-smart" data-user="<%= current_user.id %>" data-username="<%= current_user.username %>" data-image="<%= current_user.image_location %>">Post Something Smart</a></li>
        <li><a class='post-something-short' data-post="something-short" data-user="<%= current_user.id %>" data-username="<%= current_user.username %>" data-image="<%= current_user.image_location %>">Post Something Short</a></li>
        <li><a class='post-something-long' data-post="something-long" data-user="<%= current_user.id %>" data-username="<%= current_user.username %>" data-image="<%= current_user.image_location %>">Post Something Long</a></li>
        <li><a class='post-something-latin' data-post="something-latin" data-user="<%= current_user.id %>" data-username="<%= current_user.username %>" data-image="<%= current_user.image_location %>">Post Something in Latin</a></li>
        <li><a>Post Image</a></li>
      </ul>
  </div>
</div>
<hr />
<h3 class="text-center">Timeline</h3>
<div class="row">
  <div class="scrollable">
    <table id="status-table" class="">
      <% @statuses.each do |status| %>
        <tr>
          <% @votes = status.get_upvotes.size + status.get_downvotes.size %>
          <td><i class='upvote fa fa-arrow-up' data-status="<%= status.id %>" data-voter="<%= current_user.username %>"></i><div id="score<%= status.id %>"> &nbsp;<%= @votes %></div><i class='downvote fa fa-arrow-down' data-status="<%= status.id %>"></i></td>
          <td><img src="<%= status.user.image_location %>"/></td><td> <a href="<%= user_path(status.user.username) %>"><%= status.user.username %></a> says: <br> <%= status.status_update %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/user/show.html.erb
<div class="row">
  <table id="status-table">
 <div class="small-3 columns">
   <img src="<%= @user.image_location %>" />
   <%= link_to 'Add Friend', add_friend_path(@user.username) %>
 </div>
 <div class="small-9 columns">
   <%= @user.name %><br>
   <i>"<%= @user.username %>"</i><br>
   <%= @user.city %>, <%= @user.state %>, <%= @user.country %><br>
   Born on <%= @user.birthday.strftime('%b %d, %Y') %><br>
   <%= Time.now.year.to_i - @user.birthday.strftime('%Y').to_i%> years old<br>
   <%= @user.gender %><br>
 </div>
</div>
<hr />
<div class="row">
  <table>
    <% @statuses.each do |status| %>
    <% @votes = status.get_upvotes.size + status.get_downvotes.size %>
    <tr>
      <td><i class='upvote fa fa-arrow-up' data-status="<%= status.id %>" data-voter="<%= current_user.username %>"></i><div id="score<%= status.id %>"> &nbsp;<%= @votes %></div><i class='downvote fa fa-arrow-down' data-status="<%= status.id %>"></i></td>
      <td> <%= status.user.username%> says: <br> <%= status.status_update %></td>
    </tr>
    <% end %>
  </table>
</div>

app/views/welcome/index.html.erb
<div class='index-page-top'>
  <h1 class='intro-to-page'> Welcome to Fakebook! </h1>
  <h4 class='second-intro'>Sign up and never control your life again... </h4>
</div>